version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin ${repository_url}
  build:
    commands:
      - DATE=`date +%Y-%m-%d`
      - COMMIT_ID=$(git log -n 1 --format=%H)
      - docker build -t ${repository_url}:$DATE -t ${repository_url}:$COMMIT_ID -t ${repository_url}:latest .
  post_build:
    commands:
      - echo post_build
      - docker push ${repository_url}
      - echo ----------------------------------------------------------
      - echo ${repository_url}:$COMMIT_ID としてイメージをプッシュしました
      - echo ----------------------------------------------------------
