name: DeployProductionWebFront

on:
  workflow_dispatch:

jobs:
  build:
    name: Deploy Production Web Front
    runs-on: ubuntu-latest
    env:
      S3_BUCKET_URL: s3://review.swiswiswift.com
      CLOUD_FRONT_DISTRIBUTION_ID: E3EK69PNKIEPZ1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PRODUCTION_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PRODUCTION_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Deploy to S3
        run: |
          aws s3 sync web_front/html $S3_BUCKET_URL --exact-timestamps --delete
      - name: Delete Chaches
        run: |
          aws cloudfront create-invalidation --distribution-id $CLOUD_FRONT_DISTRIBUTION_ID --paths "/*"
